
import java.awt.Color;
import java.awt.Component;
import java.awt.Cursor;
import java.awt.Desktop;
import java.awt.Frame;
import java.io.File;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.net.URL;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonModel;
import javax.swing.ImageIcon;
import javax.swing.JEditorPane;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author prathibha
 */
public class ConInterface extends javax.swing.JFrame {

    /**
     * Creates new form ConInterface
     */
    public static ReportFinal reportf=new ReportFinal();
    public static File[] files = null;
    public static File[] filesSI = null;
    public static String ZipPath = null;
    File files2 = null;
    File files3 = null;
    CountAny ca=new CountAny();
    
    String SelectImage = null;
    
    TextTry tt=new TextTry();
    //ArrayList<String> fields = new ArrayList<String>();
    ArrayList<String> field = tt.addArray();
    
    
    
    int xmouse;
    int ymouse;
    
    public ConInterface() {
        initComponents();
        tfSaveFilePath.disable();
        tfSelectFilePath.disable();
        setnoofcon();
        lbluserIDShow.setText(tt.getUserID(field));
        lblUserNameShow.setText(tt.getUname(field));
        //System.out.println(field);
        //System.out.println(tt.getPath1(field));
        //System.out.println(tt.getPath2(field));
        //System.out.println(tt.getUname(field));
        //System.out.println(tt.getUserID(field));
    }
    
    public void setnoofcon(){
        
        lblnoofconvdidShow.setText(ca.getCounttolable());
    }
    
    public  void resetinterface(){
        files = null;
        ZipPath = null;
        files2 = null;
        files3 = null;
        tfSelectFilePath.setText("");
        tfSaveFilePath.setText("");
        lblNoofImages.setText("0");
        cbAge.setSelectedIndex(0);
        cbArea.setSelectedIndex(0);
        cbWeight.setSelectedIndex(0);
        buttonGroup1.clearSelection();
   
    }
    
    public void setFields(ArrayList arry){
        
    }
    
    public int isSetAllFields(){
        
        if(cbAge.getSelectedIndex()!=0){
            if(buttonGroup1.getSelection()!=null){
                if(cbArea.getSelectedIndex()!=0){
                    return 1;
                }else{
                    //.showMessageDialog(null, "no area selected");
                    MessageBox mb=new MessageBox("Please select Area","Warning Message");
                    mb.setVisible(true);
                    return 0;
                }
            }else{
                //JOptionPane.showMessageDialog(null, "select male or female");
                MessageBox mb=new MessageBox("Please select gender","Warning Message");
                mb.setVisible(true);
                return 0;
            }
        }else{
            //JOptionPane.showMessageDialog(null, "no age selected");
            MessageBox mb=new MessageBox("Please select age category","Warning Message");
            mb.setVisible(true);
            return 0;
        }
        
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        lblminimize = new javax.swing.JLabel();
        lblClose = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        lblblueBar = new javax.swing.JLabel();
        lblProgetTitle = new javax.swing.JLabel();
        SelectImages = new javax.swing.JLabel();
        btnBrowseImages = new javax.swing.JButton();
        tfSelectFilePath = new javax.swing.JTextField();
        lblNoOfSelectedImages = new javax.swing.JLabel();
        lblNoofImages = new javax.swing.JLabel();
        lblUserID = new javax.swing.JLabel();
        lbluserIDShow = new javax.swing.JLabel();
        lblUserName = new javax.swing.JLabel();
        lblUserNameShow = new javax.swing.JLabel();
        lblNoofCondid = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblnoofconvdidShow = new javax.swing.JLabel();
        lblAge = new javax.swing.JLabel();
        lblSex = new javax.swing.JLabel();
        lblweight = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblArea = new javax.swing.JLabel();
        cbWeight = new javax.swing.JComboBox<>();
        cbAge = new javax.swing.JComboBox<>();
        cbArea = new javax.swing.JComboBox<>();
        rbMale = new javax.swing.JRadioButton();
        rbFemale = new javax.swing.JRadioButton();
        lblSaveDirectory = new javax.swing.JLabel();
        tfSaveFilePath = new javax.swing.JTextField();
        btnBrowseImages1 = new javax.swing.JButton();
        btnConvert = new javax.swing.JButton();
        btnUpload = new javax.swing.JButton();
        lblbackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(750, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblminimize.setFont(new java.awt.Font("Helvetica", 1, 24)); // NOI18N
        lblminimize.setText("-");
        lblminimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblminimizeMousePressed(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblminimizeMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblminimizeMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblminimizeMouseEntered(evt);
            }
        });
        getContentPane().add(lblminimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(705, 7, 17, 20));

        lblClose.setFont(new java.awt.Font("Avenir Next", 1, 18)); // NOI18N
        lblClose.setText("X");
        lblClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblCloseMousePressed(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCloseMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCloseMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCloseMouseEntered(evt);
            }
        });
        getContentPane().add(lblClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(727, 7, 17, 20));

        lblTitle.setFont(new java.awt.Font("Helvetica Neue", 0, 20)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setText("DATA COLLECTION FOR FACIAL TISSUE THICKNESS MEASUREMENT");
        getContentPane().add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 650, 40));

        lblblueBar.setBackground(new java.awt.Color(0, 133, 255));
        getContentPane().add(lblblueBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 750, 60));

        lblProgetTitle.setFont(new java.awt.Font("Avenir", 0, 18)); // NOI18N
        lblProgetTitle.setForeground(new java.awt.Color(204, 204, 204));
        lblProgetTitle.setText("Neuroimaging Data Portal for DICOM Data Management");
        getContentPane().add(lblProgetTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, -1, -1));

        SelectImages.setFont(new java.awt.Font("Avenir", 0, 14)); // NOI18N
        SelectImages.setForeground(new java.awt.Color(204, 204, 204));
        SelectImages.setText("Select Images");
        getContentPane().add(SelectImages, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 155, -1, 40));

        btnBrowseImages.setFont(new java.awt.Font("Avenir", 0, 14)); // NOI18N
        btnBrowseImages.setText("...");
        btnBrowseImages.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrowseImagesActionPerformed(evt);
            }
        });
        getContentPane().add(btnBrowseImages, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 347, 50, -1));

        tfSelectFilePath.setBackground(new java.awt.Color(204, 204, 204));
        tfSelectFilePath.setBorder(null);
        tfSelectFilePath.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        tfSelectFilePath.setSelectionColor(new java.awt.Color(0, 153, 255));
        getContentPane().add(tfSelectFilePath, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 165, 360, 20));

        lblNoOfSelectedImages.setFont(new java.awt.Font("Avenir", 0, 14)); // NOI18N
        lblNoOfSelectedImages.setForeground(new java.awt.Color(204, 204, 204));
        lblNoOfSelectedImages.setText("No of Selected ");
        getContentPane().add(lblNoOfSelectedImages, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 210, -1, 20));

        lblNoofImages.setFont(new java.awt.Font("Avenir", 0, 48)); // NOI18N
        lblNoofImages.setForeground(new java.awt.Color(0, 153, 255));
        lblNoofImages.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNoofImages.setText("0");
        getContentPane().add(lblNoofImages, new org.netbeans.lib.awtextra.AbsoluteConstraints(547, 250, 120, 70));

        lblUserID.setFont(new java.awt.Font("Avenir", 0, 14)); // NOI18N
        lblUserID.setForeground(new java.awt.Color(204, 204, 204));
        lblUserID.setText("User_ID:");
        getContentPane().add(lblUserID, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, -1, -1));

        lbluserIDShow.setFont(new java.awt.Font("Avenir", 0, 14)); // NOI18N
        lbluserIDShow.setForeground(new java.awt.Color(204, 204, 204));
        lbluserIDShow.setText("RG00001");
        getContentPane().add(lbluserIDShow, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, -1, -1));

        lblUserName.setFont(new java.awt.Font("Avenir", 0, 14)); // NOI18N
        lblUserName.setForeground(new java.awt.Color(204, 204, 204));
        lblUserName.setText("User Name:");
        getContentPane().add(lblUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 120, -1, -1));

        lblUserNameShow.setFont(new java.awt.Font("Avenir", 0, 14)); // NOI18N
        lblUserNameShow.setForeground(new java.awt.Color(204, 204, 204));
        lblUserNameShow.setText("MR.Wasala");
        getContentPane().add(lblUserNameShow, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 120, -1, -1));

        lblNoofCondid.setFont(new java.awt.Font("Avenir", 0, 14)); // NOI18N
        lblNoofCondid.setForeground(new java.awt.Color(204, 204, 204));
        lblNoofCondid.setText("No of Convertions did:");
        getContentPane().add(lblNoofCondid, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, -1, -1));

        jSeparator1.setBackground(new java.awt.Color(102, 102, 102));
        jSeparator1.setForeground(new java.awt.Color(153, 153, 153));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 90, 740, -1));

        lblnoofconvdidShow.setFont(new java.awt.Font("Avenir", 0, 14)); // NOI18N
        lblnoofconvdidShow.setForeground(new java.awt.Color(255, 255, 255));
        lblnoofconvdidShow.setText("10");
        getContentPane().add(lblnoofconvdidShow, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 470, -1, -1));

        lblAge.setFont(new java.awt.Font("Avenir", 0, 14)); // NOI18N
        lblAge.setForeground(new java.awt.Color(204, 204, 204));
        lblAge.setText("Age Category");
        getContentPane().add(lblAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, -1, -1));

        lblSex.setFont(new java.awt.Font("Avenir", 0, 14)); // NOI18N
        lblSex.setForeground(new java.awt.Color(204, 204, 204));
        lblSex.setText("Sex");
        getContentPane().add(lblSex, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 240, 30, -1));

        lblweight.setFont(new java.awt.Font("Avenir", 0, 14)); // NOI18N
        lblweight.setForeground(new java.awt.Color(204, 204, 204));
        lblweight.setText("Weight Categoty");
        getContentPane().add(lblweight, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, -1, -1));

        jLabel1.setFont(new java.awt.Font("Avenir", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Images :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(583, 225, -1, -1));

        lblArea.setFont(new java.awt.Font("Avenir", 0, 14)); // NOI18N
        lblArea.setForeground(new java.awt.Color(204, 204, 204));
        lblArea.setText("Area");
        getContentPane().add(lblArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, -1, -1));

        cbWeight.setBackground(new java.awt.Color(0, 153, 255));
        cbWeight.setFont(new java.awt.Font("Avenir", 0, 14)); // NOI18N
        cbWeight.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Weight ", "30-40", "40-50", "50-60", "60-70", "70-80", "80-90", "90-100", "100-110", "110-120" }));
        getContentPane().add(cbWeight, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 300, 240, -1));

        cbAge.setBackground(new java.awt.Color(0, 153, 255));
        cbAge.setFont(new java.awt.Font("Avenir", 0, 14)); // NOI18N
        cbAge.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Age", "18-20", "20-30", "30-40", "40-50", "50-60", "60-70", "70-80" }));
        cbAge.setAutoscrolls(true);
        getContentPane().add(cbAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 210, 240, -1));

        cbArea.setBackground(new java.awt.Color(0, 153, 255));
        cbArea.setFont(new java.awt.Font("Avenir", 0, 14)); // NOI18N
        cbArea.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Area", "Ampara", "Anuradhapura", "Badulla", "Batticaloa", "Colombo", "Galle", "Gampaha", "Hambantota", "Jaffna", "Kalutara", "Kandy", "Kegalle", "Kilinochchi", "Kurunegala", "Mannar", "Matale", "Matara", "Monaragala", "Mullaitivu", "Nuwara Eliya", "Polonnaruwa", "Puttalam", "Ratnapura", "Trincomalee", "Vavuniya" }));
        getContentPane().add(cbArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 270, 240, -1));

        buttonGroup1.add(rbMale);
        rbMale.setFont(new java.awt.Font("Avenir", 0, 14)); // NOI18N
        rbMale.setForeground(new java.awt.Color(204, 204, 204));
        rbMale.setText("Male");
        getContentPane().add(rbMale, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 240, -1, -1));

        buttonGroup1.add(rbFemale);
        rbFemale.setFont(new java.awt.Font("Avenir", 0, 14)); // NOI18N
        rbFemale.setForeground(new java.awt.Color(204, 204, 204));
        rbFemale.setText("Female");
        getContentPane().add(rbFemale, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 240, -1, -1));

        lblSaveDirectory.setFont(new java.awt.Font("Avenir", 0, 14)); // NOI18N
        lblSaveDirectory.setForeground(new java.awt.Color(204, 204, 204));
        lblSaveDirectory.setText("Save Directory");
        getContentPane().add(lblSaveDirectory, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 350, -1, -1));

        tfSaveFilePath.setBackground(new java.awt.Color(204, 204, 204));
        tfSaveFilePath.setBorder(null);
        tfSaveFilePath.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        tfSaveFilePath.setSelectionColor(new java.awt.Color(0, 153, 255));
        getContentPane().add(tfSaveFilePath, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 350, 360, 20));

        btnBrowseImages1.setFont(new java.awt.Font("Avenir", 0, 14)); // NOI18N
        btnBrowseImages1.setText("Browse..");
        btnBrowseImages1.setMaximumSize(new java.awt.Dimension(90, 31));
        btnBrowseImages1.setMinimumSize(new java.awt.Dimension(90, 29));
        btnBrowseImages1.setPreferredSize(new java.awt.Dimension(90, 31));
        btnBrowseImages1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrowseImages1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnBrowseImages1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 161, 80, 30));

        btnConvert.setFont(new java.awt.Font("Avenir", 0, 14)); // NOI18N
        btnConvert.setText("Convert..");
        btnConvert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConvertActionPerformed(evt);
            }
        });
        getContentPane().add(btnConvert, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 400, -1, -1));

        btnUpload.setFont(new java.awt.Font("Avenir", 0, 14)); // NOI18N
        btnUpload.setText("Upload to Web");
        btnUpload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUploadActionPerformed(evt);
            }
        });
        getContentPane().add(btnUpload, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 400, -1, -1));

        lblbackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background-mainInterface.png"))); // NOI18N
        lblbackground.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                lblbackgroundMouseDragged(evt);
            }
        });
        lblbackground.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblbackgroundMousePressed(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblbackgroundMouseClicked(evt);
            }
        });
        getContentPane().add(lblbackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBrowseImages1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrowseImages1ActionPerformed
    //select all image files to be converted and zipped.
    //put files array all files directories
        
        JFileChooser chooser = new JFileChooser(tt.getPath1(field));//file chooser #1
        //"/Users/prathibha/Desktop/untitledfolder"
        chooser.setMultiSelectionEnabled(true);
        chooser.setFileSelectionMode( JFileChooser.FILES_AND_DIRECTORIES);
        int returnvalue= chooser.showOpenDialog(null);
        
        if (returnvalue == JFileChooser.APPROVE_OPTION) {
            if (chooser.getSelectedFile().isDirectory()) {

                SelectImage = chooser.getSelectedFile().getAbsolutePath();

                File folder = new File(SelectImage);
                files = folder.listFiles();

                System.out.println("ab path "+ SelectImage);
                //files = chooser.getSelectedFiles();
                files2 = chooser.getSelectedFile();
                tfSelectFilePath.setText(files2.getAbsolutePath());
                tfSelectFilePath.disable();
                System.out.println("length-" + files.length);
                for (int i = 0; i < files.length; i++) {
                    System.out.println("" + files[i]);
                }

                lblNoofImages.setText(Integer.toString(files.length));
            } else if (chooser.getSelectedFile().isFile()) {
                SelectImage = chooser.getSelectedFile().getAbsolutePath();

                //File folder = new File(SelectImage);
                //files = folder.listFiles();

                //System.out.println("ab path "+ SelectImage);
                files = chooser.getSelectedFiles();
                files2 = chooser.getSelectedFile();
                tfSelectFilePath.setText(files2.getAbsolutePath());
                tfSelectFilePath.disable();
                System.out.println("length-" + files.length);
                for (int i = 0; i < files.length; i++) {
                    System.out.println("" + files[i]);
                }

                lblNoofImages.setText(Integer.toString(files.length));
            }
        }
        
    }//GEN-LAST:event_btnBrowseImages1ActionPerformed

    private void btnConvertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConvertActionPerformed
        // TODO add your handling code here:
        //System.out.println("length- " + files.length);
        
        //reportf.setNoofimages(lblNoOfSelectedImages.getText());
        if (files != null) {
            if (isSetAllFields() != 0) {
                if (files3 != null) {
                    
                    //ConfirmationMessage cm =new ConfirmationMessage("wcwc", "ewfwec");
                    //cm.setVisible(true);
                    //int p = cm.returnv();
                    
                    //int p = JOptionPane.showConfirmDialog(null, "Do you really want to back to login screen?", "Back to login", JOptionPane.YES_NO_OPTION,JOptionPane.INFORMATION_MESSAGE);
                    //System.out.println(cm);
                    //if(p==0){
                        
                       
                        setnoofcon();
                        
                        reportf.setAgecategory((String) cbAge.getSelectedItem());
                        reportf.setNoofimages(lblNoofImages.getText());
                        reportf.setUserid(lbluserIDShow.getText());
                        if(rbFemale.isSelected()){
                            reportf.setSex(rbFemale.getText());
                        }else{
                            reportf.setSex(rbMale.getText());
                        }
                        
                        System.out.println(rbFemale.isSelected());
                        reportf.setArea((String) cbArea.getSelectedItem());
                        reportf.setWeightcategory((String) cbWeight.getSelectedItem());
                        ConProcess cp = new ConProcess();
                        cp.setVisible(true);
                        resetinterface();
                    
                    //}
                    //JOptionPane.show
                    
                    
                } else {
                    //JOptionPane.showMessageDialog(rootPane, "nodirectorySelected");
                    MessageBox mb=new MessageBox("Please select the save path","Warning Message");
                    mb.setVisible(true);
                }
            }

        } else {
            //JOptionPane.showMessageDialog(rootPane, "nofilesSelected");
            MessageBox mb=new MessageBox("Please select DICOM images","Warning Message");
            mb.setVisible(true);
        }
        
        
    }//GEN-LAST:event_btnConvertActionPerformed

    private void btnBrowseImagesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrowseImagesActionPerformed
        // TODO add your handling code here:
        
        
        JFileChooser chooser = new JFileChooser(tt.getPath2(field));//file choosern #2
        System.out.println(tt.getPath2(field));
        chooser.setMultiSelectionEnabled(true);
        chooser.setFileSelectionMode( JFileChooser.DIRECTORIES_ONLY);
        int returnvalue= chooser.showOpenDialog(null);
        
        if (returnvalue == JFileChooser.APPROVE_OPTION) {
            files3 = chooser.getSelectedFile();
            tfSaveFilePath.setText(files3.getAbsolutePath());
            tfSaveFilePath.disable();
            ZipPath = files3.getAbsolutePath();
            
        }
        
        
    }//GEN-LAST:event_btnBrowseImagesActionPerformed

    private void lblCloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseEntered
        // TODO add your handling code here:
        setCursor(Cursor.HAND_CURSOR);
        lblClose.setForeground(Color.white);
    }//GEN-LAST:event_lblCloseMouseEntered

    private void lblCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseClicked
        // TODO add your handling code here:
        lblClose.setForeground(Color.LIGHT_GRAY);
        System.exit(0);
    }//GEN-LAST:event_lblCloseMouseClicked

    private void lblCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseExited
        // TODO add your handling code here:
        setCursor(Cursor.DEFAULT_CURSOR);
        lblClose.setForeground(Color.black);
    }//GEN-LAST:event_lblCloseMouseExited

    private void lblCloseMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMousePressed
        // TODO add your handling code here:
        lblClose.setForeground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_lblCloseMousePressed

    private void lblminimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblminimizeMouseClicked
        // TODO add your handling code here:
        lblminimize.setForeground(Color.LIGHT_GRAY);
        setState(Frame.ICONIFIED);
    }//GEN-LAST:event_lblminimizeMouseClicked

    private void lblminimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblminimizeMouseEntered
        // TODO add your handling code here:
        setCursor(Cursor.HAND_CURSOR);
        lblminimize.setForeground(Color.white);
    }//GEN-LAST:event_lblminimizeMouseEntered

    private void lblminimizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblminimizeMouseExited
        // TODO add your handling code here:
        setCursor(Cursor.DEFAULT_CURSOR);
        lblminimize.setForeground(Color.black);
    }//GEN-LAST:event_lblminimizeMouseExited

    private void lblminimizeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblminimizeMousePressed
        // TODO add your handling code here:
        lblminimize.setForeground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_lblminimizeMousePressed

    private void lblbackgroundMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblbackgroundMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_lblbackgroundMouseClicked

    private void lblbackgroundMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblbackgroundMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-xmouse, y-ymouse);
    }//GEN-LAST:event_lblbackgroundMouseDragged

    private void lblbackgroundMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblbackgroundMousePressed
        // TODO add your handling code here:
        xmouse = evt.getX();
        ymouse = evt.getY();
    }//GEN-LAST:event_lblbackgroundMousePressed

    private void btnUploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUploadActionPerformed
        // TODO add your handling code here:
        if (Desktop.isDesktopSupported()) {
            try {
                Desktop.getDesktop().browse(new URI("http://faceid.lk/neuroimagingdataportal"));
            } catch (IOException ex) {
                Logger.getLogger(ConInterface.class.getName()).log(Level.SEVERE, null, ex);
            } catch (URISyntaxException ex) {
                Logger.getLogger(ConInterface.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnUploadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel SelectImages;
    private javax.swing.JButton btnBrowseImages;
    private javax.swing.JButton btnBrowseImages1;
    private javax.swing.JButton btnConvert;
    private javax.swing.JButton btnUpload;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbAge;
    private javax.swing.JComboBox<String> cbArea;
    private javax.swing.JComboBox<String> cbWeight;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblArea;
    private javax.swing.JLabel lblClose;
    private javax.swing.JLabel lblNoOfSelectedImages;
    private javax.swing.JLabel lblNoofCondid;
    private javax.swing.JLabel lblNoofImages;
    private javax.swing.JLabel lblProgetTitle;
    private javax.swing.JLabel lblSaveDirectory;
    private javax.swing.JLabel lblSex;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUserID;
    private javax.swing.JLabel lblUserName;
    private javax.swing.JLabel lblUserNameShow;
    private javax.swing.JLabel lblbackground;
    private javax.swing.JLabel lblblueBar;
    private javax.swing.JLabel lblminimize;
    private javax.swing.JLabel lblnoofconvdidShow;
    private javax.swing.JLabel lbluserIDShow;
    private javax.swing.JLabel lblweight;
    private javax.swing.JRadioButton rbFemale;
    private javax.swing.JRadioButton rbMale;
    private javax.swing.JTextField tfSaveFilePath;
    private javax.swing.JTextField tfSelectFilePath;
    // End of variables declaration//GEN-END:variables
}
